---
title: "First Post"
date: 2018-01-16T12:39:11+02:00
draft: false
---

* Introduction

Hello there, brave soul! This scary-looking thing here is actually a tutorial, whose aim is in fact to make our everyday lives way easier! How you ask? We shall learn how to install and use the Linux Operating System, as well as some additional tools, the most important of which is Emacs! Too many unknown words? Well, fear not dear friend, for I shall help guide you through this computer-geek dungeon, and thus give you access to the ultimate truth of a *fast-paced working environment*!

Sounds nice and all, but... why use Linux instead of another OS (operating system, like Windows, or MacOS)? Well, there are a lot of reasons, but here's a list of the main ones:

- Linux is an Open-source OS :: It's completely free, no charges. But, there must be a catch, right? Nope. It has all the features you can need in an operating system and is fully hardware compatible. Isn't that great already?
- It's also a very light OS :: It works on way less RAM than any other OS, leaving processing power for other applications to use, which makes them run faster. Hence, no high-end system is needed to run it.
- Updates are made easy :: For the most part, those can run in the background, while you work on more urgent tasks of yours. No reboot needed either!
- It has a highly customizable nature :: For those of us that enjoy tweaking the looks of our working environment, Linux offers a variety of options to change and adjust to your liking almost every part of its interface.
- Secure and private foundation :: Most Linux distributions don't collect your data at all. Therefore, you will not be needing additional tools to protect your privacy.
- And friendly community support :: Facing a problem with your OS? Support is easy to find through a plethora of forums and chat rooms, full of Linux users happy to help you sort things out!

In general, we're talking about a highly reliable OS, that's definitely worth a try. Even most of the Internet giants like Google and Facebook run on Linux. Besides, let's be real here, to whom doesn't the idea of no more "blue screens of death" sound liberating?

So! You were promised speed in your everyday computer usage. Here's how we'll be able to achieve that: by combining Linux with Emacs, a free text editor, that can be used to do way more than just plain text writing!

Let's get started then, shall we?

* Getting started with Linux

** Installation

We are going to be installing the Manjaro distribution of Linux, since it provides all the benefits of the Arch operating system, combined with a focus on user-friendliness and accessibility. Its nature makes it suitable for newcomers, as well as experienced Linux users.

First off, we need to download the .iso file from the web. You can find it [[https://manjaro.org/get-manjaro/][here]],  under *Manjaro XFCE Edition (17.1.2)*. Choose the one that says *Manjaro XFCE 64-bit* (either via Torrent, or Direct Download).

Once downloaded, we need to burn the .iso file to an empty USB flash drive. That can be easily done by using any piece of software that creates bootable USB flash drives. [[https://unetbootin.github.io/][UNetbootin]] is one of the many utilities you can use to do just that.

When that is done, you have to reboot your system from the flash drive you just burned our .iso file in to, and follow the instructions to install Manjaro into your computer. In case additional help is needed, do not hesitate to have a look [[https://wiki.manjaro.org/index.php?title=Main_Page][here]], under the *Installation* headline.

You are ready to go!

** Terminal Emulator

In Linux, it is very easy to manage software packages. We will be using the  [[https://wiki.manjaro.org/index.php?title=Pacman][Pacman]] package manager to install software. To do that, we need to open the *Terminal Emulator* (which you can access through the Manjaro icon on the bottom of the screen), and run this particular command: *sudo pacman -S [software package name]*

#+BEGIN_SRC sh
sudo pacman -S tmux
sudo pacman -S emacs
#+END_SRC
We'll have to install a couple of packages in our system, *tmux*, a terminal multiplexer that lets us switch easily between several programs in one terminal, and *emacs*, the infamous text editor that we've been talking about earlier.

And here, we have a list of some very basic commands you can use in order to navigate through the terminal:

+ *sudo* : run a command as admin
+ *sudo pacman -S* : install package (ex: sudo pacman -S chromium - installs the open source browser on which the Chrome browser is based)
+ *&* : runs an application in the background (try running the command: firefox & - on the terminal and see what happens!)
+ *pwd* : see which directory you are currently in
+ *~* : access the home directory
+ *ls* : list the files inside the directory you are currently in
+ *cd* : change directory (ex: cd /home/user/Documents/ - gets you to the Documents directory)
+ *mkdir* : create a directory (ex: mkdir newFolder)
+ *rmdir* : delete a directory (ex: rmdir newFolder)
+ *touch* : create a file (ex: touch notes.txt - creates a .txt file named notes)
+ *rm* : delete a file (ex: rm notes.txt)
+ *cp* : copy file to another location (ex: cp notes.txt /home/user/Documents/ - copies the .txt file to the Documents directory)
+ *mv* : move file to another location (ex: mv notes.txt /home/user/Desktop - moves the .txt file to the Desktop directory)
+ *locate* : search a file (ex: locate notes.txt)
+ *man* : lets you know how a command is used (ex: man pacman - will show you the user manual for the command pacman)

** Keyboard Shortcuts

Since we got to use some commands on the terminal, let me talk to you about one of the general ideas behind working in such an environment. The aim is to get used to working more with the *keyboard*, and less with our mouse. That way, we not only get to work way faster (once accustomed to using commands instead of dragging the mouse on icons in order to do our job), but also work way more efficiently. I know it's hard to get used to not using your mouse, but let me make it a bit easier for you by offering a small list of shortcuts you can begin to experiment with, in order to limit your mouse usage as much as possible for the time being, until you get accustomed enough with the keyboard you won't actually want to use the mouse anymore:

+ *alt tab* : change between application
+ *alt f4* : close the currently active program
+ *alt f10* : window at full screen
+ *Ctrl N* : create new blank document in currently active program
+ *Ctrl O* : open a file in currently active program
+ *Ctrl F* : open find window for currently active window
+ *Ctrl A* : select all text
+ *Ctrl C* : copy selected text
+ *Ctrl X* : cut selected text
+ *Ctrl V* : paste selected text
+ *Ctrl S* : save current document file
+ *Ctrl Z* : undo last action
+ *Ctrl Y* : redo last action

That way, even if you do not feel ready to jump straight into Linux, and need a bit more time to get yourself prepared, you can stick to your old OS and practice using your keyboard a little more than before.

* Getting to know Emacs

** Just what exactly is Emacs?

Emacs is an extensible, customizable, self-documenting, real-time display editor, with over 10,000 built-in commands whose user interface allows the user to combine into macros to automate work. It's basically like any other text editor you think? Actually, it's just that on the surface, but way way cooler when you get to realize just how many things you can do in it! For instance, apart from editing plain text, you can also manage your emails, your files, your meetings through a built-in journal, open a terminal shell, create music, heck, even build whole sites for the web in seconds!

You can start by launching Emacs, either through the Manjaro menu icon, or by running the command *emacs &* inside the terminal. Remember how we talked about customizability, right? Well, doesn't that overly simple, white interface bores you? How about we get you a bit familiar with the way Emacs does things by trying out a very simple first command that lets us load a theme of our liking? Press *Alt-x*, type *load-theme*, then press Enter. There, you can find a list of some of Emacs default themes. Choose one by using the up and down arrow keys, and press Enter. And voila! You just ran your very first command in Emacs! In case you're interested in more themes, you can find some nice alternatives [[https://emacsthemes.com/][here]]. Please note that what the theme we just loaded is temporary, and won't be saved. In order to make Emacs remember it, you'll need to write a little bit of code.

#+BEGIN_SRC sh
cd ~
mkdir Dev
cd /home/username/Dev
git clone https://github.com/iani/emacs-prelude.git
#+END_SRC
An alternative to that can be to clone a ready Emacs configuration using the terminal. And that's exactly what we're going to do. You'll have to visit [[https://github.com/iani/emacs-prelude][this]] gitHub page, click on the *Clone or download* green button, and copy to clipboard the web URL provided. Once done, open the terminal, and, using the commands provided earlier, get to home directory, create in there a directory where all of your code will be put, access this new directory, and clone the configuration using the URL we just copied.

For more convenience and clarity, you could create another directory inside Dev named emacs, for all the code concerning emacs, and clone the configuration there. That could be a nice small exercise, in order to get you used to the terminal commands.

It is important to note that this particular configuration (provided by Dr Ioannis Zannos, Professor of Computer Music and Interactive Media Arts at the Ionian University) offers some very helpful tweaks that can and will make working in emacs easier and faster, enhancing our experience in a productive way. The whole tutorial is based upon this configuration. Let me show you what I mean: press Ctrl-x and wait for a few seconds. A window will appear listing all the possible key combinations, as well as the commands these combinations give access to. Pretty neat, huh?

** A whole new world of Commands

I know that sounds hellishly difficult, but please try to not freak out! Yes, we're talking about a lot of key combinations, and even if they appear to be hard to understand, they are built upon logic, which will make their understanding and memorization way easier. For example, as you'll soon realize, the key used for a specific command is usually the first letter of the word that summarizes what this command does (like in this case: Ctrl-n gets you to the Next line). Another example is that, while Ctrl is usually used for something that has to do with the smaller scale, Alt does the same job in the large scale (Alt-e gets you to the End of the current paragraph, just like Ctrl-e gets you to the End of the current line).

Let's start with the basics. Emacs builds its key combinations upon four modal keys:

+ *C* : control key, ctrl
+ *M* : meta keys, atl/esc
+ *H* : hyperkey, fn
+ *S* : superkey, windowskey or equivalent

We will be using C a lot, and a bit of M. As you noticed, the meta keys are two, escape and alt. I will be using alt for the sake of convenience, but esc is also a viable option.

As we mentioned before, *Emacs works with commands*. We can run the command by name, as we did for load-theme, by using *M-x* and typing the command, or we can use keyboard key combinations to access each one of them. As you can imagine, the second option is way more productive than the first one, so that's what we're gonna use.

Because of the sheer number of commands Emacs has, and since the total amount of two-keys combinations is limited, we'll get to learn about combinations that need three, four, or even more keys to execute a command. Before that, you'll need to remember this golden command that you can use whenever something goes wrong while using very complex key combinations, or when you've simply used a wrong command and want to escape:

+ *C-g* : go, escape! in case you're stuck
+ *C-M-c* : alternative for C-g

Now that that's settled, here are the most commonly used combinations upon which are based more advanced commands:

+ *C-x* : gives access to the tree of commands that have to do with files, buffers, windows, the emacs application itself, and emacs shells
+ *C-c* : gives access to the tree of commands that are context related i.e dependent on the currently active mode (for example, shell mode, or SuperCollider mode which is addressed later on) and the position of the cursor inside the buffer
+ *C-h* : gives access to a tree of help commands (basically gets us out of the mud!)

** Taking notes in Emacs

Let's start with something easy. In order to better understand the commands that are about to follow, we'll be creating an text file to be able to try them out, which can be done by using the terminal (remember that, in order to create a file, you have to get into the directory where you want said file to be situated, and run the command touch; give the new file the name myNotes.org - we'll explain later why .org). To open the said file inside Emacs, we need to use *C-x d* to change our directory. Press Enter, and find where you created your myNotes.org file (if you followed my example on organizing files, your new text file should be in /home/user/Workfiles). Press Enter once again to open it, and you'll be met with an empty file. There, paste some random text from the internet (while copying in Linux is C-c, emacs uses another set of key shortcuts; use C-y for paste), and try out these following commands:

*** To move around without needing your mouse:

+ *C-+* : (or ctrl + shift + =) zoom *in*
+ *C--* : zoom *out*
+ *C-n* : go to the *next* line
+ *C-p* : go to the *previous* line
+ *C-f* : go *forwards* one step (alternative to right arrow)
+ *C-b* : go *backwards* one step (alternative to left arrow)
+ *M-f* : go forwards one word
+ *M-b* : go backwards one word
+ *C-a* : go to the *beginning* of current line
+ *C-e* : go to the *end* of current line
+ *M-a* : go to the beginning of current paragraph
+ *M-e* : go to the end of current paragraph
+ *C-l* : align current line with view (in the middle of the window)
+ *C-s* : jump to a word by *searching* it by its first letter
+ *C-v* : go to the next page (alternative to the mouse's scroll wheel)
+ *M-v* : go to the previous page (alternative to the mouse's scroll wheel)
+ *M-<* : (or alt + shift + ,) go to the beginning of the buffer
+ *M->* : (or alt + shift + .) go to the end of the buffer

*** To edit text:

Keep in mind that *Enter* and *Backspace* work in the same way as outside Emacs.

Let's say you want to put your randomly pasted text under a headline called "Random Stuff". Try writing it like that, on top of your text: *Random Stuff. You've created a headline. Adding more stars before its title, you can create subsections, in order to arrange your notes in a more neat way.

+ *M-w* : copy (if a text area is not specified, it'll copy the current line)
+ *C-w* : cut (same goes for cut)
+ *C-y* : paste
+ *C-d* : delete one character (from the right of our cursor)
+ *M-d* : delete one word (from the right of our cursor)
+ *C-k* : delete, *kill* the rest of the line, what's right from the cursor (it is also copied to clipboard)
+ *C-/* : undo your last action
+ *C-x u* : access the undo tree
+ *C-@* : (or ctrl + shift + 2) : by using the arrows, select a region of text
+ *C-M-Shift-Arrows* : move said region of text, or current bullet/paragraph if no region is selected
+ *C-%* : (or ctrl + shift + 5) : replace a word with another in selection
+ *M-%* : replace a word with another one by one (y for replace, n for next one)
+ *C-\* : change to Greek language inside emacs

*** The prefix C-u

This prefix C-u is one of those cool little add-ons that Emacs can use, which help us be even more precise in what we do. Here's a couple of examples that should help you understand how to use this prefix:

+ *C-u 5 C-n* : remember how C-n gets us to the next like? Using this prefix and a number 'x' before C-n, we can go 'x' lines forwards, here 5.
+ *C-u 3 C-d* : using the same logic, we know that C-d deletes one character. Here, it deletes 3 characters at once.

Try using negative numbers, or other commands and see what happens! If you end up messing up your text, don't forget that you can undo your actions by using C-/.

** Using Org Mode

Great! Now that we know the shortcuts to some pretty basic commands, let's talk about the infamous Org Mode. Remember when we created the file myNotes.org? Well, this is a text file where we can write using Org Mode. That's exactly what we just got a taste of, in the *Some elementary level Commands* section.

Emacs works with Modes. Every buffer (for now, think of the buffer as a window, just like the one you were in when editing your text, and you'll understand later what it is) possesses a major mode, which determines the editing behavior of Emacs while that buffer is current. The mode line, on the bottom of the screen, normally shows the name of the current major mode, in bold letters (if you're still editing your text in Emacs, it should write *Org* there, indicating the mode Emacs is currently in).

Org Mode is for keeping notes, maintaining TODO lists, planning projects, and authoring documents with a fast and effective plain-text system. We solemnly explored its ability to keep notes until now, but if you're interested in examining its other capacities, there's a [[https://orgmode.org/org.html][manual]] that could help you do that (with a [[https://orgmode.org/guide/][compact]] version available, in case the complete one seems too complicated for now).

*** Additional headline Commands

+ *C-Enter* : create new headline at the end of current section at the same level
+ *M-Enter* : create new headline or bullet at current level at cursor location
+ *M-left/rightArrow* : alter the place of current section in the hierarchy
+ *M-Shift-left/rightArrow* : alter the place of current section and its subsections in the hierarchy
+ *C-c C-n / C-c C-p* : go to next / previous headline
+ *M-n / M-p* : go to next / previous visible headline
+ *C-c C-b / C-c C-f* : go to next / previous headline at the same level
+ *C-c C-j* : jump to headline using search
+ *C-M-]* : while cursor on headline, toggle access to the information under said headline

*** Using babel

Let's say you have an .org file with notes about the Python programming language, and need to include both the theoretical aspects, and some code examples. Here's where Babel comes in to save the day. Programming languages can live in blocks inside natural language Org-mode documents. Babel is about letting many different languages work together. In other words, you can have your theory and practice inside the same document, and even edit and run that code in real time, or export it, depending on the language you're using.

+ *type '<' followed by 's' and then press tab* : insert new babel block, and indicate the language you'll be using in said block
+ *type '#+begin src language' on new line, '#+end src' a couple of lines later* : alternative way to insert a block, with 'language' being the one you want to code with, like python, or ruby for example
+ *C-c '* : open current babel block on separate window
+ *while in babel window, C-c C-c* : close babel window and return to main .org file

*** Navigating in Org mode

As was mentioned before, Emacs can be used to do a variety of things. One of the main reasons to use it though should be *how easy it is to organize and search through one's files*.

Before digging into that further, please allow me to clarify something: In everyday life, you can get to a certain place through many different roads. That rule applies in Emacs as well; you can do something in many different ways. There's no right or wrong, just a more convenient way for each one of us separately. Here, in this tutorial, I will try to present you many different ways to do something you want, but as far as organizing the files in your system goes, I will propose my way of doing so, which I find most easy to navigate through. Personally, I prefer to stick to two folders: one for my notes, with attachments (which I name Workfiles), and one for my code (which I name Dev).

But what exactly are these attachments? Let's say you have an .org file where you keep your notes on theatre studies, and you need to attach the Macbeth play .pdf to your Shakespeare headline, in order to be able to access it directly from there. That .pdf will become an attachment, and be put in a folder created especially for it. Here's the most important key combination you have to remember, as far as attachments are concerned:

+ *C-c C-a* : displays a menu with a list of commands regarding attachments

There, you can choose to execute one of the following main commands:

+ *a* : select and attach an already existing file
+ *n* : create a new attachment (ex test.org)
+ *o* : open the attachment(s)
+ *f* : open the folder containing the attachments

Once you've created an attachment, you will see that an *ATTACH* will appear next to (or under, depending on the size of your window) your headline. For you to access the properties block (or attachments info), go to said ATTACH, and press *tab*. Same goes for closing the block.

Another way to gain access to that .pdf file would be to create a link with using the documentation of the command org-attach-method:

+ *ln* : create a hard link
+ *lns* : create a symbol link

Awesome! Now that that's done with, here are some *specific search commands* that lets us navigate through our notes and code files in a very fast and easy way.

+ *C-s* : simple i-search (searches in the visible part of our text)
+ *C-u C-c C-w* : jump to headline (level 1 only)
+ *C-c i* : i-menu up to level 2 headlines (headlines only)
+ *C-c C-j* : searches only in headlines, up to org-goto-maxlevel (headlines only)
+ *C-c h o* : helm-occur type and search in headlines (text and headlines)
+ *C-Shift s* : helm-swoop type and search in whole file (text and headlines)
+ *M-x, icicle-imenu* : displays all headlines, and search by writing
+ *M-x, icy-mode* : toggle icy-mode, incompatible with org mode (for more information on this one, read the documentation about the command icy-mode itself)

I personally use more C-s, C-c h o, and the icicle-imenu ones, but it is up to you to try them out and decide which suits you better.

There are also commands that allow you to search for files, or words, through entire projects of yours:

+ *C-c p f* : find file in the project you are currently in
+ *C-c p s s* : silver search, find text in project you are currently in
+ *C-c p p* : switch project, press *A* for silver search

The last very useful feature I find pretty helpful in terms of navigation is the use of *bookmarks*. By easily creating a bookmark, you can gain fast access to some folders or files you use rather often.

+ *C-x r m* : create bookmark for current location
+ *C-x j j* : jump to bookmark

** Other useful Commands

*** Functions concerning buffers, files, and windows

+ *C-x b* : buffer list
+ *C-c r* : change name of current file and buffer
+ *C-x d* : change directory
+ *C-x C-c* : cancel, close Emacs

+ *C-x C-f* : find file open
+ *C-x C-s* : save file
+ *C-x C-w* : write file (save as)
+ *C-x C-d* : see file content
+ *C-x d* : see and edit file content

+ *C-x o* : go to other window
+ *C-x 0* : close current window
+ *C-x 1* : make current window fullscreen
+ *C-x 2* : split window vertically
+ *C-x 3* : split window horizontally

*** Dired Mode Commands

+ *Shift-c* : copy file to
+ *Shift-r* : rename file
+ *Shift-d* : delete file
+ *Shift-s* : symbolic link to
+ *Shift-m* : mark files
+ *Shift-u* : remove marks
+ *g* : refresh

*** Some Context-specific (Mode-specific) Commands

+ *C-c* : customize context
+ *C-c C-c* : context of context

+ *C-x M-m* : open shell window
+ *C-c C-c* : save changes
+ *C-x C-q* : edit mode

* SuperCollider in Emacs

** What is SuperCollider?

SuperCollider is a platform for audio synthesis and algorithmic composition, used by musicians, artists, and researchers working with sound. The sclang used is an efficient and expressive dynamic programming language providing a framework for interactive programming and live coding.

#+BEGIN_SRC sh
sudo pacman -S SuperCollider
#+END_SRC
Emacs has the ability to open a buffer on SuperCollider mode, allowing you to work within its environment without needing any other application working simultaneously. To do that, we need to already have SuperCollider in our system, so we'll need to download and install it using Pacman.

#+BEGIN_SRC
git clone https://github.com/iani/sc-hacks.git
#+END_SRC
Dr Zannos we mentioned before provides a personal library of SC code examples named [[https://github.com/iani/sc-hacks][sc-hacks]]. I would suggest to clone its contents to your Dev directory if desired, since it proposes some interesting techniques to work with.

In case you're new to SuperCollider, and are interested in learning how to code in sclang, you can access CCRMA's (Center for Computer Research in Music and Acoustics) free [[https://ccrma.stanford.edu/~ruviaro/texts/A_Gentle_Introduction_To_SuperCollider.pdf][tutorial]]. You could also check out and try to understand, or even experiment with other people's code that you can find in [[https://sccode.org/][sccode]].

** Basic Commands of SuperCollider in Emacs

When in SC mode, just like with any other mode in Emacs, we have to use *context-specific commands*.

+ *C-c M-s* : access SuperCollider mode
+ *C-c* : everything that has to do with SC mode, while in it
+ *C-c Shift-w* : open a Workspace
+ *C-c C-p b* : boot the server
+ *C-c C-p q* : quit
+ *C-c C-c* : play our function
+ *C-c C-s* : stop

A very helpful feature in SC mode is that of *snipets //:*, since we can use them as blocks of code we can easily jump to and off, and also run.

+ *M-n* : jump to next snipet
+ *M-p* : jump to previous snipet
+ *C-M-x* : run current snipet

Remember that we can also use *babel* inside any .org file to create a block of code using sclang.

** Example of SC Code in Emacs

Here's a very basic example of a function that generates a looping sound in sclang.

#+BEGIN_SRC sclang
//:
{
	var synths, amp, amp1;
	amp = Pseq([0.01!5, 0.1].flat, inf).asStream;
	loop {
		amp1 = amp.next;
		synths = {{SinOsc.ar(400 rrand: 4000, 0, amp1)}.play} ! 10;
		0.05.wait;
		synths do: _.free;
		0.05.wait;
	}
}.fork
//:
#+END_SRC

* Hugo in Emacs

** What is Hugo?

#+BEGIN_SRC sh
sudo pacman -S hugo
#+END_SRC
Hugo is a *flat-file website generation system*. That means that it does not use a database. Instead, it generates plain html files. Flat-file websites have the advantage of being safer (since databases are prone to hacking attempts) and faster (because there's no need to access a database to get the data). Hugo uses markdown and org-mode as source text format. An advantage of using a simple markup language as source is that you can always regenerate the site from the source, and you can use the source also for other types of exports (pdf, etc.). That's exactly how this tutorial you're reading was created! We'll need to install it in our system using Pacman (opt pygmentize).

#+BEGIN_SRC sh
sudo pacman -S go
#+END_SRC
Hugo is a program written in go language ([[https://golang.org/][golang]]), a programming language designed by Google that is object oriented, fast, and geared for concurrent online systems. Go takes a collection of source text files written in markdown or org-mode and translates them to html. As a result, hugo produces a website consisting of html files, linked to css and javascript files, which define the style of the site. In short, go is an open source programming language that makes it easy to build simple, reliable, and efficient software. We'll need to install go as well.

In order to make sure that everything works just fine with Go, you can open a babel block inside your notes and try out this [[https://wiki.archlinux.org/index.php/Go#Test_your_installation][test your installation tutorial]] provided by the Arch Linux Wiki.

** Create your first site

Once you're sure everything is ready, go try to create your first web site using hugo's [[https://gohugo.io/getting-started/quick-start/][quick-start guide]].

** Using the DocuAPI theme

#+BEGIN_SRC
git submodule add https://github.com/bep/docuapi.git themes/docuapi
echo 'theme = "docuapi"' >> config.toml
echo 'baseURL = "http://yourdomain.com"' >> config.toml
echo '[params]' >> config.toml
echo 'search = true' >> config.toml
#+END_SRC
You can choose from a variety of hugo [[https://themes.gohugo.io/][themes]] in order to create a website that suits your personal needs. In that case, you'll need to modify the line of code concerning the theme. You could use DocuAPI, which is the one I've used for this website, since it's the only one where everything is written in a single .org file (other themes need different .org files for every post inside their site). For DocuAPI to work properly, you'll need to rename theme.toml to config.toml, and add using the terminal the theme, baseURL, and search parameters.

#+BEGIN_SRC sh
hugo server -D
hugo
#+END_SRC
In order to be able to edit your site using Org mode, you'll need to rename the post you created to something.org. You can also run the command *hugo server -D* into shell to see your site being created step by step, simply by refreshing the page once you introduce a new element into the .org file. When done with creating your site, you can export it to html by simply running the command *hugo* in the shell. But be careful! If you want it to appear as you created it to be published in your domain online, you need to change the *draft* to *false* inside your .org post before exporting it. Else, you'll only be able to see it while in localhost.

* Keeping our notes Accessible

Since our tutorial draws to an end and we wanted to cover all bases concerning a fast-paced working experience, we cannot dismiss talking about [[https://github.com/][GitHub]]. GitHub is one of those tools programmers use for their archives. It becomes a necessity since *it makes accessing your files easier, and protects them from getting lost*. It also makes working in group projects as simpler as possible! Why? Because the code uploaded is accessible by everybody, at anytime, online. That way, you have access to see, download, and edit, code created by other people.

In a larger sense, GitHub contributes to the efforts made worldwide to distribute the idea of open source software, i.e. whose code is made available for anybody to ameliorate it, thus helps to make crucial progress in computer sciences. We've already had a taste of how powerful of a tool it can be, since we cloned and have been using some pretty neat configuration for emacs made by someone else.

#+BEGIN_SRC sh
xclip -sel clip < ~/path/to/file.txt
#+END_SRC
Emacs can be used to easily upload our files in a matter of seconds. First, in order to connect to the GitHib server, you'll need to create an account, go to settings, and generate an SSH key (/home/user/.ssh/id_rsa).

Now you're ready to make your first commit and push it online. You can do that either on the shell, or emacs. While inside your .org file in emacs, do the following:

#+BEGIN_SRC sh
git add .
git commit -am "message"
git push origin master
#+END_SRC
1. *C-x g*
2. go to *Unstaged Changes*
3. *s c c* to commit
4. name the commit and *C-c C-c* to execute
5. *Shift-p p* to push

And you're done! Your notes are now online and accessible :)

* Finish Line!

And done! You've successfully completed the computer-geek dungeon! I sincerely thank you for your attention.

Until next time, brave adventurer!
